### ISSUE TITLE
Add rounding?

### ISSUE THREAD

**Issue by GollyJer** [pizzafox/convert#150]
Hi. I found your package today and it's excellent. Thanks so much for putting it together.

One thing I'm always having to do is rounding for display purposes. I'm curious if you'd be interested in adding `round` and/or `toFixed` with decimal places to your package.

My thinking is that everyone doing these conversions needs to also round for display purposes.

About 6 months ago I tested many solutions and settled on this for speed and accuracy.

```javascript 
// Modified version of Solution #2 from https://stackoverflow.com/a/48764436/25197.
// Fast and accurate.
const DecimalMath = (() => {
  const decimalAdjust = (type, num, decimalPlaces) => {
    const precision = 10 ** decimalPlaces;
    const n = num * precision * (1 + Number.EPSILON);
    return Math[type](n) / precision;
  };

  return {
    round(num: number, decimalPlaces = 0) {
      return decimalAdjust('round', num, decimalPlaces);
    },

    // Format using fixed-point notation.
    toFixed(num: number, decimalPlaces = 0) {
      return decimalAdjust('round', num, decimalPlaces).toFixed(decimalPlaces);
    },

    ceil(num: number, decimalPlaces = 0) {
      return decimalAdjust('ceil', num, decimalPlaces);
    },

    floor(num: number, decimalPlaces = 0) {
      return decimalAdjust('floor', num, decimalPlaces);
    },

    trunc(num: number, decimalPlaces = 0) {
      return decimalAdjust('trunc', num, decimalPlaces);
    },
  };
})();

export default DecimalMath;
``` 

To see the round and toFixed functions in action click the `Run Code Snippet` button on [this stackoverflow answer](https://stackoverflow.com/a/64383436/25197). There are 30 answers on that page and I went through the comments in each one to find the places where each answer broke and made sure my version worked correctly.

I imagine a version of `convert` that can do this.
```javascript 
convert(150).from('pound').to('kilogram').round(2)
```

If any of this seems reasonable and you want me to take a stab at a PR I can do that as well.

**Comment by adx59** [comment]
Thank you for opening this issue!!

**Comment by pizzafox** [comment]
Unfortunately doing

```js
convert(123).from('x').to('y').round(2);
```
isn't (easily) possible since the return value is a plain `number` or `bigint`.

The most reasonable alternative seems like providing a method used like so:

```js
import { round, convert } from 'convert';

round(convert(123).from('x').to('y'), 2);
```
But that's just a generic rounding function, not specific to converting units and probably doesn't belong in this library.

Also isn't `DecimalMath.toFixed(x, y)` just doing `x.toFixed(y)`, or am I missing something?

**Comment by GollyJer** [comment]
`Number.toFixed()` rounds [incorrectly](https://stackoverflow.com/questions/10015027/javascript-tofixed-not-rounding) and `Math.round()` rounds to the integer level eliminating decimal accuracy.

Regarding `DecimalMath.toFixed()`... 
it basically adds zeros if necessary but uses the `decimalAdjust` to do accurate rounding.

Back to `convert`...
I don't quite follow what you mean by "...return value is a plain number...". Here's an exact example I'm working with.
```javascript 
console.log(convert(175).from('pounds').to('kilograms')); // 79.37866475
```
And I think it would be great to have an easy way to access an accurately rounded value at the decimal level. Maybe just a simple method?

```javascript 
export function decimalRound(numberToRound, digits = 0) {
  const precision = 10 ** digits;
  const n = numberToRound * precision * (1 + Number.EPSILON);
  const roundedNumber = Math.round(n) / precision;
  return roundedNumber;
}
```

You could add it as an export but a continuation method would be awesome.

```javascript 
console.log(convert(175).from('pounds').to('kilograms')).decimalRound(2); // 79.38
```

I understand if you think rounding doesn't makes sense in your package.  We can agree to disagree. 😀
Closing this issue will let me know. No biggie. Thanks.

**Comment by pizzafox** [comment]
By "return value is a plain number" I meant that adding a round function to it would look something like

```js
function decimalRound(numberToRound, digits = 0) {
  const precision = 10 ** digits;
  const n = numberToRound * precision * (1 + Number.EPSILON);
  const roundedNumber = Math.round(n) / precision;
  return roundedNumber;
}

// ...

let result = 123;

result.decimalRound = digits => decimalRound(result, digits);
```

You would need to be defining a new function on the result number. Modifying the number object to do so is not something I want to do because I oppose it in principle. Eventually [the pipeline operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Pipeline_operator) can solve this problem in an elegant and performant way.

---

Anyway, rounding functions like you provided absolutely have a valuable use. I actually didn't know that `num.toFixed()` wasn't properly rounding until now...

I appreciate this issue and your feedback, but convert doesn't seem like the appropriate place to have such rounding utilities. I'd recommend publishing your own package that exports the rounding functions you want and I could add in a note to the readme of common recipes with convert for displaying pretty output.

**Comment by GollyJer** [comment]
Good feedback. Makes perfect sense. Thanks!
